### ISSUE TITLE
github.copilot.enable being reset

### ISSUE THREAD

**Issue by asheroto** [mattickx/copilotignore-vscode#2]
Hey again!

So I know that you recently introduced the ability for `github.copilot.enable` to reset force load, but I discovered an issue. I tried turning off completions for "JSON" and "JSONC" files by setting these to false:

![image](https://github.com/mattickx/copilotignore-vscode/assets/49938263/16771ad7-e595-41ff-91cb-21566eb15f0e)

But after saving, they are changed to `true`. If I disable your extension, they continue to remain false.

In this case, it's actually forcing copilot to not-ignore files. 😁

**Comment by asheroto** [comment]
~As a side note, you may have some competition~. [Found this](https://marketplace.visualstudio.com/items?itemName=disable-copilot-comment-completions.disable-copilot-comment-completions), just thought you'd want to be aware. 😊

Update: doesn't look like it actually disables Copilot though, so not competition... but you might consider adjusting the keywords for your extension so if someone searches "disable copilot" it would show your extension! 😊

**Comment by mathieumagalhaes** [comment]
> ~As a side note, you may have some competition~. [Found this](https://marketplace.visualstudio.com/items?itemName=disable-copilot-comment-completions.disable-copilot-comment-completions), just thought you'd want to be aware. 😊

It's not competition as I'm not commercialising it. A better solution is always welcome.

> I tried turning off completions for "JSON" and "JSONC" files by setting these to false:

Stipulated in [README ](https://github.com/mattickx/copilotignore-vscode?tab=readme-ov-file#%EF%B8%8F-limitations) that this extension is an all or nothing kind of deal.
Custom config of github.copilot.enable in global settings can't be configured.

We could add a `copilotignore.whitelist` setting or something to take into account a custom setup.
Which would be a drop-in replacement for your jsonc & json usecase.

I won't have much free time this week to work on this, a PR is always welcome and appreciated.

**Comment by asheroto** [comment]
> It's not competition as I'm not commercialising it. A better solution is always welcome.

Oh I know, I didn't mean literally. 😊 Just thought I'd make you aware in case not.

> Stipulated in [README ](https://github.com/mattickx/copilotignore-vscode?tab=readme-ov-file#%EF%B8%8F-limitations) that this extension is an all or nothing kind of deal.

Ah I had not read the updated readme.

> Custom config of github.copilot.enable in global settings can't be configured.

What is the purpose of forcing the settings? Is it just to make sure someone doesn't have it disabled or misconfigured?

**Comment by mathieumagalhaes** [comment]
> > It's not competition as I'm not commercialising it. A better solution is always welcome.
> 
> Oh I know, I didn't mean literally. 😊 Just thought I'd make you aware in case not.
> 
> > Stipulated in [README ](https://github.com/mattickx/copilotignore-vscode?tab=readme-ov-file#%EF%B8%8F-limitations) that this extension is an all or nothing kind of deal.
> 
> Ah I had not read the updated readme.
> 
> > Custom config of github.copilot.enable in global settings can't be configured.
> 
> What is the purpose of forcing the settings? Is it just to make sure someone doesn't have it disabled or misconfigured?

The global enable setting is what makes this extension work.
I don't remember exactly the edge-case I was running into that made me want to override the entire global enable setting, instead of just `github.copilot.enable.*`.

I'm closing this issue, I'm open to pull requests if you find something more optimized.
