### ISSUE TITLE
Would it be possible to make the extention block copilot chat from accessing the file? 

### ISSUE THREAD

**Issue by Glitch-Cloud-Code** [mattickx/copilotignore-vscode#3]
Basically the title. Currently I can see the autocomplete being blocked, but if I ask the chat to describe what's in the file - it gladly outputs it to me.

**Comment by mathieumagalhaes** [comment]
I've checked out the settings available for the "Github Copilot Chat" extension.
![image](https://github.com/mattickx/copilotignore-vscode/assets/9006731/56638dfa-e921-4ecc-aef5-f3dba4f876c2)

There is no enable/disable for the chat itself, so I don't think it is possible by external modification.

This could be a good addition to the discussion on: https://github.com/orgs/community/discussions/10305
I would suggest you to add your feature request there.

I'm closing this issue, but feel free to comment if you think I'm missing something.
