### ISSUE TITLE
Folder with multiple nested source control repositories

### ISSUE THREAD

**Issue by rgr21** [mattickx/copilotignore-vscode#9]
Scenario: vscode opens a folder with layout

> a
> a/b
> a/b/.git
> a/b/.copilotignore
> a/b/secret.token
> a/c
> a/c/.git
> a/c/.copilotignore
> a/c/secret.token

Ideally copilotignore would detect and respect both .copilotignore files.
It would currently only recognise one in a/.copilotignore (or in $HOME/.copilotignore.)

I think vscode exposes source control repositories to allow implementing this in a straight forward manner.

**Comment by rgr21** [comment]
vscode api not as nice as I had hoped for - have to fish in the git plugin. Because that is part of standard vscode install, hopefully it is acceptable.
(Based on master, will update for you if you merge the other PR?)

**Comment by mathieumagalhaes** [comment]
If I understand correctly, this would limit functionality to Git repositories only.
I'd prefer if .copilotignore could apply recursively based on its own path, similar to how .gitignore files work,
but without being restricted to Git repository structures. 

Ideally, it would work across any folder structure, including non-Git repositories.
It probably is possible to do with the current npm dependency `ignore` we are already using.

I previously added a note about this in the README:
```Make .copilotignore take into account it's own path/location (apply patterns recursive)```

Would this be something you'd consider looking into? @rgr21

**Comment by mathieumagalhaes** [comment]
Also note that in your root .copilotignore file you can already add something like: `a/b/**`.
Or a variation to it to ignore files recursively.

See ([df296f3](https://github.com/mattickx/copilotignore-vscode/commit/df296f3f3b650b2396ae05c39ecab901562cfba9))

**Comment by rgr21** [comment]
The motivating use case is where I have two source control repositories checked out both of which contain their own .copilotignore file. A user then opens the parent folder of both (which isn't vcs managed, and contains no other files). I'd like the .copilotignore files to be honoured.
I can provide a PR that switches from doing git based file finding to just walking all folders under workspace? In general I don't like file-system walking, which is why I leant on the existing mechanic. Either works though, so happy to take your steer.
I like the idea mentioned of recursive pattern, will do as a separate PR if that is OK?

**Comment by rgr21** [comment]
Recursive pattern does need to be included here. Two seemingly valid approaches:
- Have one set of patterns, but prefix each pattern with relative path before adding. This fails because whilst "*.OLD" matches a.OLD wherever in the tree it is found, "DISABLE/*.OLD" does not match DISABLE/NESTED/a.OLD.
- Have multiple sets of patterns, and use all appropriate ones for each file based on its location.

**Comment by mathieumagalhaes** [comment]
> * Have one set of patterns, but prefix each pattern with relative path before adding. This fails because whilst "_.OLD" matches a.OLD wherever in the tree it is found, "DISABLE/_.OLD" does not match DISABLE/NESTED/a.OLD.

There is ```**/*.OLD``` you can use ? 
With the double asterix to include `any folder in between`, just like git ignore.

Does that solve your use case ?

**Comment by rgr21** [comment]
In the example .copilotignore file in this repo (prior to the adding the DISABLE/ bit) you had e.g. '\*.OLD'
That used to match any .OLD file, whereas would now need to be **/*.OLD to match, making this a breaking change. That is fine for my use cases, the code is certainly simpler doing it that way. (I had it implemented that way, sadly didn't push to a branch, but could switch back fairly quickly).

**Comment by mathieumagalhaes** [comment]
I didn't take a look at the PR yet, I thought this was the actual behaviour with `ignore` package.
Give me some time to dive in more in the upcomming days.

This might also be worth looking into:
https://github.com/microsoft/vscode-extension-samples/blob/6446fd7012bd1f7ef107683e09e488e943e668ef/chat-sample/src/tools.ts#L55-L70

**Comment by mathieumagalhaes** [comment]
> In the example .copilotignore file in this repo (prior to the adding the DISABLE/ bit) you had e.g. '*.OLD' That used to match any .OLD file, whereas would now need to be **/*.OLD to match, making this a breaking change. That is fine for my use cases, the code is certainly simpler doing it that way. (I had it implemented that way, sadly didn't push to a branch, but could switch back fairly quickly).

Also `*.OLD` still works for me with latest version, even for the file inside the DISABLE folder ?

**Comment by rgr21** [comment]
Sorry. I meant in a design where we have
workspace/
workspace/a/.copilotignore
workspace/b/.copilotignore

We want patterns in a/.copilotignore to only take effect under a/
Pretend a/.copilotignore contains "\*.OLD". We would want to exclude workspace/a/code.OLD but allow workspace/b/code.OLD.
The approach in the PR is to maintain separate map of patterns.
The first approach I tried was to have one set of patterns, but to insert "a/*.OLD" rather than "\*.OLD" when reading the .copilotignore file from a/
That superficially works, and the code is far cleaner, but won't match a/nested/code.OLD, which is the break I was cautious of.

**Comment by mathieumagalhaes** [comment]
> Sorry. I meant in a design where we have workspace/ workspace/a/.copilotignore workspace/b/.copilotignore
> 
> We want patterns in a/.copilotignore to only take effect under a/ Pretend a/.copilotignore contains "*.OLD". We would want to exclude workspace/a/code.OLD but allow workspace/b/code.OLD. 

Ah yes that is a functionallity I would have liked to add.

> The approach in the PR is to maintain separate map of patterns. The first approach I tried was to have one set of patterns, but to insert "a/*.OLD" rather than "*.OLD" when reading the .copilotignore file from a/ That superficially works, and the code is far cleaner, but won't match a/nested/code.OLD, which is the break I was cautious of.

I'll take a look at your PR as soon as I can.

**Comment by mathieumagalhaes** [comment]
Merged into master 👍

**Comment by rgr21** [comment]
Thanks - master looks good to me. A release would be much appreciated when you have time.

**Comment by mathieumagalhaes** [comment]
> Thanks - master looks good to me. A release would be much appreciated when you have time.

Build 0.1.9 is available on the Market Place! 👍
